export const mockProducts = [
  {
    id: 1,
    title: "Smartphone X",
    price: 799.99,
    description: "Latest model with advanced camera features",
    category: "electronics",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.5, count: 120 },
  },
  {
    id: 2,
    title: "Laptop Pro",
    price: 1299.99,
    description: "High performance laptop for professionals",
    category: "electronics",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.8, count: 85 },
  },
  {
    id: 3,
    title: "Wireless Headphones",
    price: 149.99,
    description: "Noise cancelling wireless headphones",
    category: "electronics",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.3, count: 210 },
  },
  {
    id: 4,
    title: "Men's T-Shirt",
    price: 19.99,
    description: "Comfortable cotton t-shirt",
    category: "clothing",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.0, count: 150 },
  },
  {
    id: 5,
    title: "Women's Jeans",
    price: 49.99,
    description: "Slim fit jeans for women",
    category: "clothing",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.2, count: 95 },
  },
  {
    id: 6,
    title: "Coffee Table",
    price: 149.99,
    description: "Modern wooden coffee table",
    category: "furniture",
    image: "https://via.placeholder.com/300",
    rating: { rate: 4.6, count: 45 },
  },
];
